Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,28 +1,21 @@
 name: Build, Test, Lint, Coverage, and Documentation
 on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: ["main"]
-    types:
-      - opened
-      - synchronize
-      - reopened
+  workflow_dispatch: 
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    container: huskysat/found:latest
+  # build:
+  #   runs-on: ubuntu-latest
+  #   container: huskysat/found:latest
 
-    steps:
-    - uses: actions/checkout@v4
+  #   steps:
+  #   - uses: actions/checkout@v4
 
-    - name: Build all
-      uses: nick-fields/retry@v3.0.2
-      with:
-        max_attempts: 3
-        timeout_minutes: 3
-        command: make clean && make compile -j16
+  #   - name: Build all
+  #     uses: nick-fields/retry@v3.0.2
+  #     with:
+  #       max_attempts: 3
+  #       timeout_minutes: 3
+  #       command: make clean && make compile -j16
   
   test:
     runs-on: ubuntu-latest
@@ -41,41 +34,41 @@ jobs:
           make test OMIT_ASAN=true -j16
           valgrind ./build/bin/found-test
   
-  float:
-    runs-on: ubuntu-latest
-    container: huskysat/found:latest
+  # float:
+  #   runs-on: ubuntu-latest
+  #   container: huskysat/found:latest
 
-    steps:
-    - uses: actions/checkout@v4
+  #   steps:
+  #   - uses: actions/checkout@v4
 
-    - name: Float Build
-      uses: nick-fields/retry@v3.0.2
-      with:
-        max_attempts: 3
-        timeout_minutes: 3
-        command: make clean && make compile FLOAT_MODE=true -j16
-    - name: Float Coverage
-      uses: nick-fields/retry@v3.0.2
-      with:
-        max_attempts: 3
-        timeout_minutes: 3
-        command: make clean && make coverage FLOAT_MODE=true -j16
+  #   - name: Float Build
+  #     uses: nick-fields/retry@v3.0.2
+  #     with:
+  #       max_attempts: 3
+  #       timeout_minutes: 3
+  #       command: make clean && make compile FLOAT_MODE=true -j16
+  #   - name: Float Coverage
+  #     uses: nick-fields/retry@v3.0.2
+  #     with:
+  #       max_attempts: 3
+  #       timeout_minutes: 3
+  #       command: make clean && make coverage FLOAT_MODE=true -j16
 
-  lint:
-    runs-on: ubuntu-latest
-    container: huskysat/found:latest
+  # lint:
+  #   runs-on: ubuntu-latest
+  #   container: huskysat/found:latest
 
-    steps:
-    - uses: actions/checkout@v4
+  #   steps:
+  #   - uses: actions/checkout@v4
 
-    - name: Stylecheck
-      run: make google_stylecheck
+  #   - name: Stylecheck
+  #     run: make google_stylecheck
     
-    - name: Test Stylecheck
-      run: make google_stylecheck_test
+  #   - name: Test Stylecheck
+  #     run: make google_stylecheck_test
     
-    - name: Line Ending Check (Ensure LF)
-      uses: erclu/check-crlf@master
+  #   - name: Line Ending Check (Ensure LF)
+  #     uses: erclu/check-crlf@master
 
   coverage:
     runs-on: ubuntu-latest
@@ -91,76 +84,76 @@ jobs:
         timeout_minutes: 3
         command: make clean && make coverage -j16
     
-    - name: Upload Coverage Report
-      if: ${{ always() }}
-      uses: actions/upload-artifact@v4
-      with:
-        name: Coverage Report
-        path: build/documentation/coverage
+    # - name: Upload Coverage Report
+    #   if: ${{ always() }}
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: Coverage Report
+    #     path: build/documentation/coverage
   
-  documentation:
-    runs-on: ubuntu-latest
-    container: huskysat/found:latest
+  # documentation:
+  #   runs-on: ubuntu-latest
+  #   container: huskysat/found:latest
 
-    steps:
-    - uses: actions/checkout@v4
+  #   steps:
+  #   - uses: actions/checkout@v4
     
-    - name: Generate Documentation
-      run: |
-        make clean
-        (./build.sh cmake "" --target coverage --parallel 16) || true
-        (./build.sh cmake "" --target documentation --parallel 16)
+  #   - name: Generate Documentation
+  #     run: |
+  #       make clean
+  #       (./build.sh cmake "" --target coverage --parallel 16) || true
+  #       (./build.sh cmake "" --target documentation --parallel 16)
     
-    - name: Install rsync (for JamesIves/github-pages-deploy-action@v4)
-      run: apt install -y rsync
+  #   - name: Install rsync (for JamesIves/github-pages-deploy-action@v4)
+  #     run: apt install -y rsync
     
-    - name: Set Target Folder in documentation
-      id: set-folder
-      run: |
-        if [ "${{ github.ref_name }}" = "main" ]; then
-          echo "TARGET_FOLDER=." >> $GITHUB_ENV
-        else
-          echo "TARGET_FOLDER=${{ github.ref_name }}" >> $GITHUB_ENV
-        fi
-      shell: bash
+  #   - name: Set Target Folder in documentation
+  #     id: set-folder
+  #     run: |
+  #       if [ "${{ github.ref_name }}" = "main" ]; then
+  #         echo "TARGET_FOLDER=." >> $GITHUB_ENV
+  #       else
+  #         echo "TARGET_FOLDER=${{ github.ref_name }}" >> $GITHUB_ENV
+  #       fi
+  #     shell: bash
     
-    - name: Upload Pages Artifact
-      uses: JamesIves/github-pages-deploy-action@v4
-      with:
-        branch: documentation
-        folder: build/documentation/
-        target-folder: ${{ env.TARGET_FOLDER }}
+    # - name: Upload Pages Artifact
+    #   uses: JamesIves/github-pages-deploy-action@v4
+    #   with:
+    #     branch: documentation
+    #     folder: build/documentation/
+    #     target-folder: ${{ env.TARGET_FOLDER }}
   
-  cmake-build-all:
-    runs-on: ubuntu-latest
-    container: huskysat/found:latest
+  # cmake-build-all:
+  #   runs-on: ubuntu-latest
+  #   container: huskysat/found:latest
 
-    steps:
-    - uses: actions/checkout@v3
+  #   steps:
+  #   - uses: actions/checkout@v3
 
-    - name: Build all
-      uses: nick-fields/retry@v3.0.2
-      with:
-        max_attempts: 3
-        timeout_minutes: 3
-        command: ./build.sh clean && ./build.sh cmake "" --parallel 16
+  #   - name: Build all
+  #     uses: nick-fields/retry@v3.0.2
+  #     with:
+  #       max_attempts: 3
+  #       timeout_minutes: 3
+  #       command: ./build.sh clean && ./build.sh cmake "" --parallel 16
 
-  cmake-float:
-    runs-on: ubuntu-latest
-    container: huskysat/found:latest
+  # cmake-float:
+  #   runs-on: ubuntu-latest
+  #   container: huskysat/found:latest
 
-    steps:
-    - uses: actions/checkout@v4
+  #   steps:
+  #   - uses: actions/checkout@v4
 
-    - name: Float Build
-      uses: nick-fields/retry@v3.0.2
-      with:
-        max_attempts: 3
-        timeout_minutes: 3
-        command: |
-          ./build.sh clean
-          ./build.sh cmake -DFLOAT_MODE=ON --target compile --parallel 16
-          ./build.sh cmake -DFLOAT_MODE=ON --target coverage --parallel 16
+  #   - name: Float Build
+  #     uses: nick-fields/retry@v3.0.2
+  #     with:
+  #       max_attempts: 3
+  #       timeout_minutes: 3
+  #       command: |
+  #         ./build.sh clean
+  #         ./build.sh cmake -DFLOAT_MODE=ON --target compile --parallel 16
+  #         ./build.sh cmake -DFLOAT_MODE=ON --target coverage --parallel 16
   
   cmake-test:
     runs-on: ubuntu-latest
